INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (1, 'AF', 'Afghanistan', 93);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (2, 'AL', 'Albania', 355);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (3, 'DZ', 'Algeria', 213);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (4, 'AS', 'American Samoa', 1684);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (5, 'AD', 'Andorra', 376);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (6, 'AO', 'Angola', 244);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (7, 'AI', 'Anguilla', 1264);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (8, 'AQ', 'Antarctica', 0);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (9, 'AG', 'Antigua And Barbuda', 1268);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (10, 'AR', 'Argentina', 54);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (11, 'AM', 'Armenia', 374);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (12, 'AW', 'Aruba', 297);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (13, 'AU', 'Australia', 61);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (14, 'AT', 'Austria', 43);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (15, 'AZ', 'Azerbaijan', 994);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (16, 'BS', 'Bahamas The', 1242);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (17, 'BH', 'Bahrain', 973);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (18, 'BD', 'Bangladesh', 880);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (19, 'BB', 'Barbados', 1246);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (20, 'BY', 'Belarus', 375);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (21, 'BE', 'Belgium', 32);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (22, 'BZ', 'Belize', 501);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (23, 'BJ', 'Benin', 229);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (24, 'BM', 'Bermuda', 1441);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (25, 'BT', 'Bhutan', 975);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (26, 'BO', 'Bolivia', 591);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (27, 'BA', 'Bosnia and Herzegovina', 387);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (28, 'BW', 'Botswana', 267);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (29, 'BV', 'Bouvet Island', 0);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (30, 'BR', 'Brazil', 55);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (31, 'IO', 'British Indian Ocean Territory', 246);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (32, 'BN', 'Brunei', 673);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (33, 'BG', 'Bulgaria', 359);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (34, 'BF', 'Burkina Faso', 226);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (35, 'BI', 'Burundi', 257);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (36, 'KH', 'Cambodia', 855);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (37, 'CM', 'Cameroon', 237);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (38, 'CA', 'Canada', 1);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (39, 'CV', 'Cape Verde', 238);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (40, 'KY', 'Cayman Islands', 1345);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (41, 'CF', 'Central African Republic', 236);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (42, 'TD', 'Chad', 235);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (43, 'CL', 'Chile', 56);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (44, 'CN', 'China', 86);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (45, 'CX', 'Christmas Island', 61);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (46, 'CC', 'Cocos (Keeling) Islands', 672);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (47, 'CO', 'Colombia', 57);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (48, 'KM', 'Comoros', 269);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (49, 'CG', 'Republic Of The Congo', 242);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (50, 'CD', 'Democratic Republic Of The Congo', 242);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (51, 'CK', 'Cook Islands', 682);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (52, 'CR', 'Costa Rica', 506);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (53, 'CI', 'Cote D''Ivoire (Ivory Coast)', 225);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (54, 'HR', 'Croatia (Hrvatska)', 385);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (55, 'CU', 'Cuba', 53);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (56, 'CY', 'Cyprus', 357);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (57, 'CZ', 'Czech Republic', 420);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (58, 'DK', 'Denmark', 45);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (59, 'DJ', 'Djibouti', 253);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (60, 'DM', 'Dominica', 1767);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (61, 'DO', 'Dominican Republic', 1809);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (62, 'TP', 'East Timor', 670);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (63, 'EC', 'Ecuador', 593);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (64, 'EG', 'Egypt', 20);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (65, 'SV', 'El Salvador', 503);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (66, 'GQ', 'Equatorial Guinea', 240);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (67, 'ER', 'Eritrea', 291);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (68, 'EE', 'Estonia', 372);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (69, 'ET', 'Ethiopia', 251);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (70, 'XA', 'External Territories of Australia', 61);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (71, 'FK', 'Falkland Islands', 500);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (72, 'FO', 'Faroe Islands', 298);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (73, 'FJ', 'Fiji Islands', 679);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (74, 'FI', 'Finland', 358);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (75, 'FR', 'France', 33);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (76, 'GF', 'French Guiana', 594);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (77, 'PF', 'French Polynesia', 689);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (78, 'TF', 'French Southern Territories', 0);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (79, 'GA', 'Gabon', 241);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (80, 'GM', 'Gambia The', 220);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (81, 'GE', 'Georgia', 995);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (82, 'DE', 'Germany', 49);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (83, 'GH', 'Ghana', 233);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (84, 'GI', 'Gibraltar', 350);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (85, 'GR', 'Greece', 30);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (86, 'GL', 'Greenland', 299);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (87, 'GD', 'Grenada', 1473);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (88, 'GP', 'Guadeloupe', 590);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (89, 'GU', 'Guam', 1671);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (90, 'GT', 'Guatemala', 502);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (91, 'XU', 'Guernsey and Alderney', 44);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (92, 'GN', 'Guinea', 224);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (93, 'GW', 'Guinea-Bissau', 245);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (94, 'GY', 'Guyana', 592);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (95, 'HT', 'Haiti', 509);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (96, 'HM', 'Heard and McDonald Islands', 0);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (97, 'HN', 'Honduras', 504);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (98, 'HK', 'Hong Kong S.A.R.', 852);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (99, 'HU', 'Hungary', 36);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (100, 'IS', 'Iceland', 354);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (101, 'IN', 'India', 91);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (102, 'ID', 'Indonesia', 62);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (103, 'IR', 'Iran', 98);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (104, 'IQ', 'Iraq', 964);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (105, 'IE', 'Ireland', 353);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (106, 'IL', 'Israel', 972);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (107, 'IT', 'Italy', 39);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (108, 'JM', 'Jamaica', 1876);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (109, 'JP', 'Japan', 81);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (110, 'XJ', 'Jersey', 44);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (111, 'JO', 'Jordan', 962);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (112, 'KZ', 'Kazakhstan', 7);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (113, 'KE', 'Kenya', 254);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (114, 'KI', 'Kiribati', 686);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (115, 'KP', 'Korea North', 850);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (116, 'KR', 'Korea South', 82);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (117, 'KW', 'Kuwait', 965);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (118, 'KG', 'Kyrgyzstan', 996);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (119, 'LA', 'Laos', 856);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (120, 'LV', 'Latvia', 371);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (121, 'LB', 'Lebanon', 961);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (122, 'LS', 'Lesotho', 266);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (123, 'LR', 'Liberia', 231);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (124, 'LY', 'Libya', 218);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (125, 'LI', 'Liechtenstein', 423);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (126, 'LT', 'Lithuania', 370);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (127, 'LU', 'Luxembourg', 352);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (128, 'MO', 'Macau S.A.R.', 853);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (129, 'MK', 'Macedonia', 389);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (130, 'MG', 'Madagascar', 261);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (131, 'MW', 'Malawi', 265);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (132, 'MY', 'Malaysia', 60);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (133, 'MV', 'Maldives', 960);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (134, 'ML', 'Mali', 223);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (135, 'MT', 'Malta', 356);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (136, 'XM', 'Man (Isle of)', 44);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (137, 'MH', 'Marshall Islands', 692);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (138, 'MQ', 'Martinique', 596);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (139, 'MR', 'Mauritania', 222);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (140, 'MU', 'Mauritius', 230);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (141, 'YT', 'Mayotte', 269);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (142, 'MX', 'Mexico', 52);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (143, 'FM', 'Micronesia', 691);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (144, 'MD', 'Moldova', 373);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (145, 'MC', 'Monaco', 377);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (146, 'MN', 'Mongolia', 976);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (147, 'MS', 'Montserrat', 1664);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (148, 'MA', 'Morocco', 212);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (149, 'MZ', 'Mozambique', 258);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (150, 'MM', 'Myanmar', 95);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (151, 'NA', 'Namibia', 264);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (152, 'NR', 'Nauru', 674);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (153, 'NP', 'Nepal', 977);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (154, 'AN', 'Netherlands Antilles', 599);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (155, 'NL', 'Netherlands The', 31);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (156, 'NC', 'New Caledonia', 687);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (157, 'NZ', 'New Zealand', 64);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (158, 'NI', 'Nicaragua', 505);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (159, 'NE', 'Niger', 227);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (160, 'NG', 'Nigeria', 234);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (161, 'NU', 'Niue', 683);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (162, 'NF', 'Norfolk Island', 672);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (163, 'MP', 'Northern Mariana Islands', 1670);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (164, 'NO', 'Norway', 47);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (165, 'OM', 'Oman', 968);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (166, 'PK', 'Pakistan', 92);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (167, 'PW', 'Palau', 680);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (168, 'PS', 'Palestinian Territory Occupied', 970);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (169, 'PA', 'Panama', 507);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (170, 'PG', 'Papua new Guinea', 675);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (171, 'PY', 'Paraguay', 595);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (172, 'PE', 'Peru', 51);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (173, 'PH', 'Philippines', 63);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (174, 'PN', 'Pitcairn Island', 0);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (175, 'PL', 'Poland', 48);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (176, 'PT', 'Portugal', 351);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (177, 'PR', 'Puerto Rico', 1787);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (178, 'QA', 'Qatar', 974);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (179, 'RE', 'Reunion', 262);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (180, 'RO', 'Romania', 40);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (181, 'RU', 'Russia', 70);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (182, 'RW', 'Rwanda', 250);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (183, 'SH', 'Saint Helena', 290);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (184, 'KN', 'Saint Kitts And Nevis', 1869);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (185, 'LC', 'Saint Lucia', 1758);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (186, 'PM', 'Saint Pierre and Miquelon', 508);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (187, 'VC', 'Saint Vincent And The Grenadines', 1784);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (188, 'WS', 'Samoa', 684);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (189, 'SM', 'San Marino', 378);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (190, 'ST', 'Sao Tome and Principe', 239);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (191, 'SA', 'Saudi Arabia', 966);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (192, 'SN', 'Senegal', 221);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (193, 'RS', 'Serbia', 381);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (194, 'SC', 'Seychelles', 248);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (195, 'SL', 'Sierra Leone', 232);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (196, 'SG', 'Singapore', 65);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (197, 'SK', 'Slovakia', 421);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (198, 'SI', 'Slovenia', 386);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (199, 'XG', 'Smaller Territories of the UK', 44);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (200, 'SB', 'Solomon Islands', 677);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (201, 'SO', 'Somalia', 252);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (202, 'ZA', 'South Africa', 27);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (203, 'GS', 'South Georgia', 0);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (204, 'SS', 'South Sudan', 211);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (205, 'ES', 'Spain', 34);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (206, 'LK', 'Sri Lanka', 94);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (207, 'SD', 'Sudan', 249);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (208, 'SR', 'Suriname', 597);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (209, 'SJ', 'Svalbard And Jan Mayen Islands', 47);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (210, 'SZ', 'Swaziland', 268);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (211, 'SE', 'Sweden', 46);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (212, 'CH', 'Switzerland', 41);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (213, 'SY', 'Syria', 963);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (214, 'TW', 'Taiwan', 886);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (215, 'TJ', 'Tajikistan', 992);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (216, 'TZ', 'Tanzania', 255);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (217, 'TH', 'Thailand', 66);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (218, 'TG', 'Togo', 228);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (219, 'TK', 'Tokelau', 690);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (220, 'TO', 'Tonga', 676);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (221, 'TT', 'Trinidad And Tobago', 1868);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (222, 'TN', 'Tunisia', 216);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (223, 'TR', 'Turkey', 90);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (224, 'TM', 'Turkmenistan', 7370);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (225, 'TC', 'Turks And Caicos Islands', 1649);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (226, 'TV', 'Tuvalu', 688);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (227, 'UG', 'Uganda', 256);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (228, 'UA', 'Ukraine', 380);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (229, 'AE', 'United Arab Emirates', 971);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (230, 'GB', 'United Kingdom', 44);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (231, 'US', 'United States', 1);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (232, 'UM', 'United States Minor Outlying Islands', 1);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (233, 'UY', 'Uruguay', 598);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (234, 'UZ', 'Uzbekistan', 998);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (235, 'VU', 'Vanuatu', 678);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (236, 'VA', 'Vatican City State (Holy See)', 39);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (237, 'VE', 'Venezuela', 58);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (238, 'VN', 'Vietnam', 84);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (239, 'VG', 'Virgin Islands (British)', 1284);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (240, 'VI', 'Virgin Islands (US)', 1340);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (241, 'WF', 'Wallis And Futuna Islands', 681);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (242, 'EH', 'Western Sahara', 212);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (243, 'YE', 'Yemen', 967);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (244, 'YU', 'Yugoslavia', 38);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (245, 'ZM', 'Zambia', 260);
INSERT INTO `country` (`id`, `sort_name`, `name`, `phone_code`) VALUES (246, 'ZW', 'Zimbabwe', 263);