INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (4 ,'af','Afghanistan','Afghanistan');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (8 ,'al','Albanien','Albania');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (12 ,'dz','Algerien','Algeria');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (20 ,'ad','Andorra','Andorra');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (24 ,'ao','Angola','Angola');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (28 ,'ag','Antigua und Barbuda','Antigua and Barbuda');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (31 ,'az','Aserbaidschan','Azerbaijan');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (32 ,'ar','Argentinien','Argentina');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (36 ,'au','Australien','Australia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (40 ,'at','Österreich','Austria');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (44 ,'bs','Bahamas','Bahamas');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (48 ,'bh','Bahrain','Bahrain');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (50 ,'bd','Bangladesch','Bangladesh');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (51 ,'am','Armenien','Armenia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (52 ,'bb','Barbados','Barbados');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (56 ,'be','Belgien','Belgium');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (64 ,'bt','Bhutan','Bhutan');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (68 ,'bo','Bolivien','Bolivia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (70 ,'ba','Bosnien und Herzegowina','Bosnia and Herzegovina');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (72 ,'bw','Botswana','Botswana');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (76 ,'br','Brasilien','Brazil');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (84 ,'bz','Belize','Belize');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (90 ,'sb','Salomonen','Solomon Islands');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (96 ,'bn','Brunei','Brunei Darussalam');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (100 ,'bg','Bulgarien','Bulgaria');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (104 ,'mm','Myanmar','Myanmar');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (108 ,'bi','Burundi','Burundi');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (112 ,'by','Belarus','Belarus');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (116 ,'kh','Kambodscha','Cambodia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (120 ,'cm','Kamerun','Cameroon');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (124 ,'ca','Kanada','Canada');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (132 ,'cv','Kap Verde','Cabo Verde');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (140 ,'cf','Zentralafrikanische Republik','Central African Republic');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (144 ,'lk','Sri Lanka','Sri Lanka');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (148 ,'td','Tschad','Chad');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (152 ,'cl','Chile','Chile');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (156 ,'cn','Volksrepublik China','China');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (170 ,'co','Kolumbien','Colombia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (174 ,'km','Komoren','Comoros');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (178 ,'cg','Kongo, Republik','Congo');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (180 ,'cd','Kongo','Congo');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (188 ,'cr','Costa Rica','Costa Rica');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (191 ,'hr','Kroatien','Croatia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (192 ,'cu','Kuba','Cuba');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (196 ,'cy','Zypern','Cyprus');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (203 ,'cz','Tschechien','Czechia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (204 ,'bj','Benin','Benin');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (208 ,'dk','Dänemark','Denmark');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (212 ,'dm','Dominica','Dominica');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (214 ,'do','Dominikanische Republik','Dominican Republic');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (218 ,'ec','Ecuador','Ecuador');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (222 ,'sv','El Salvador','El Salvador');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (226 ,'gq','Äquatorialguinea','Equatorial Guinea');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (231 ,'et','Äthiopien','Ethiopia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (232 ,'er','Eritrea','Eritrea');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (233 ,'ee','Estland','Estonia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (242 ,'fj','Fidschi','Fiji');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (246 ,'fi','Finnland','Finland');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (250 ,'fr','Frankreich','France');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (262 ,'dj','Dschibuti','Djibouti');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (266 ,'ga','Gabun','Gabon');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (268 ,'ge','Georgien','Georgia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (270 ,'gm','Gambia','Gambia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (276 ,'de','Deutschland','Germany');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (288 ,'gh','Ghana','Ghana');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (296 ,'ki','Kiribati','Kiribati');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (300 ,'gr','Griechenland','Greece');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (308 ,'gd','Grenada','Grenada');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (320 ,'gt','Guatemala','Guatemala');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (324 ,'gn','Guinea','Guinea');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (328 ,'gy','Guyana','Guyana');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (332 ,'ht','Haiti','Haiti');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (340 ,'hn','Honduras','Honduras');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (348 ,'hu','Ungarn','Hungary');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (352 ,'is','Island','Iceland');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (356 ,'in','Indien','India');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (360 ,'id','Indonesien','Indonesia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (364 ,'ir','Iran','Iran');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (368 ,'iq','Irak','Iraq');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (372 ,'ie','Irland','Ireland');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (376 ,'il','Israel','Israel');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (380 ,'it','Italien','Italy');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (384 ,'ci','Elfenbeinküste','Côte d''Ivoire');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (388 ,'jm','Jamaika','Jamaica');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (392 ,'jp','Japan','Japan');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (398 ,'kz','Kasachstan','Kazakhstan');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (400 ,'jo','Jordanien','Jordan');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (404 ,'ke','Kenia','Kenya');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (408 ,'kp','Nord Korea','North Korea');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (410 ,'kr','Süd Korea','South Korea');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (414 ,'kw','Kuwait','Kuwait');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (417 ,'kg','Kirgisistan','Kyrgyzstan');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (418 ,'la','Laos','Lao');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (422 ,'lb','Libanon','Lebanon');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (426 ,'ls','Lesotho','Lesotho');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (428 ,'lv','Lettland','Latvia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (430 ,'lr','Liberia','Liberia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (434 ,'ly','Libyen','Libya');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (438 ,'li','Liechtenstein','Liechtenstein');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (440 ,'lt','Litauen','Lithuania');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (442 ,'lu','Luxemburg','Luxembourg');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (450 ,'mg','Madagaskar','Madagascar');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (454 ,'mw','Malawi','Malawi');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (458 ,'my','Malaysia','Malaysia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (462 ,'mv','Malediven','Maldives');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (466 ,'ml','Mali','Mali');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (470 ,'mt','Malta','Malta');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (478 ,'mr','Mauretanien','Mauritania');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (480 ,'mu','Mauritius','Mauritius');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (484 ,'mx','Mexiko','Mexico');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (492 ,'mc','Monaco','Monaco');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (496 ,'mn','Mongolei','Mongolia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (498 ,'md','Moldau','Moldova');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (499 ,'me','Montenegro','Montenegro');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (504 ,'ma','Marokko','Morocco');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (508 ,'mz','Mosambik','Mozambique');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (512 ,'om','Oman','Oman');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (516 ,'na','Namibia','Namibia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (520 ,'nr','Nauru','Nauru');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (524 ,'np','Nepal','Nepal');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (528 ,'nl','Niederlande','Netherlands');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (548 ,'vu','Vanuatu','Vanuatu');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (554 ,'nz','Neuseeland','New Zealand');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (558 ,'ni','Nicaragua','Nicaragua');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (562 ,'ne','Niger','Niger');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (566 ,'ng','Nigeria','Nigeria');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (578 ,'no','Norwegen','Norway');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (583 ,'fm','Mikronesien','Micronesia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (584 ,'mh','Marshallinseln','Marshall Islands');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (585 ,'pw','Palau','Palau');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (586 ,'pk','Pakistan','Pakistan');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (591 ,'pa','Panama','Panama');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (598 ,'pg','Papua-Neuguinea','Papua New Guinea');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (600 ,'py','Paraguay','Paraguay');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (604 ,'pe','Peru','Peru');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (608 ,'ph','Philippinen','Philippines');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (616 ,'pl','Polen','Poland');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (620 ,'pt','Portugal','Portugal');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (624 ,'gw','Guinea-Bissau','Guinea-Bissau');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (626 ,'tl','Osttimor','Timor-Leste');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (634 ,'qa','Katar','Qatar');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (642 ,'ro','Rumänien','Romania');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (643 ,'ru','Russland','Russian Federation');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (646 ,'rw','Ruanda','Rwanda');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (659 ,'kn','St. Kitts und Nevis','Saint Kitts and Nevis');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (662 ,'lc','St. Lucia','Saint Lucia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (670 ,'vc','St. Vincent und die Grenadinen','Saint Vincent and the Grenadines');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (674 ,'sm','San Marino','San Marino');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (678 ,'st','São Tomé und Príncipe','Sao Tome and Principe');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (682 ,'sa','Saudi-Arabien','Saudi Arabia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (686 ,'sn','Senegal','Senegal');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (688 ,'rs','Serbien','Serbia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (690 ,'sc','Seychellen','Seychelles');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (694 ,'sl','Sierra Leone','Sierra Leone');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (702 ,'sg','Singapur','Singapore');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (703 ,'sk','Slowakei','Slovakia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (704 ,'vn','Vietnam','Viet Nam');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (705 ,'si','Slowenien','Slovenia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (706 ,'so','Somalia','Somalia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (710 ,'za','Südafrika','South Africa');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (716 ,'zw','Simbabwe','Zimbabwe');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (724 ,'es','Spanien','Spain');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (728 ,'ss','Südsudan','South Sudan');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (729 ,'sd','Sudan','Sudan');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (740 ,'sr','Suriname','Suriname');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (748 ,'sz','Eswatini','Eswatini');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (752 ,'se','Schweden','Sweden');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (756 ,'ch','Schweiz','Switzerland');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (760 ,'sy','Syrien','Syrian Arab Republic');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (762 ,'tj','Tadschikistan','Tajikistan');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (764 ,'th','Thailand','Thailand');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (768 ,'tg','Togo','Togo');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (776 ,'to','Tonga','Tonga');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (780 ,'tt','Trinidad und Tobago','Trinidad and Tobago');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (784 ,'ae','Vereinigte Arabische Emirate','United Arab Emirates');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (788 ,'tn','Tunesien','Tunisia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (792 ,'tr','Türkei','Turkey');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (795 ,'tm','Turkmenistan','Turkmenistan');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (798 ,'tv','Tuvalu','Tuvalu');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (800 ,'ug','Uganda','Uganda');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (804 ,'ua','Ukraine','Ukraine');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (807 ,'mk','Nordmazedonien','North Macedonia');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (818 ,'eg','Ägypten','Egypt');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (826 ,'gb','Vereinigtes Königreich','United Kingdom');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (834 ,'tz','Tansania','Tanzania, United Republic of');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (840 ,'us','Vereinigte Staaten','United States of America');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (854 ,'bf','Burkina Faso','Burkina Faso');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (858 ,'uy','Uruguay','Uruguay');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (860 ,'uz','Usbekistan','Uzbekistan');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (862 ,'ve','Venezuela','Venezuela');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (882 ,'ws','Samoa','Samoa');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (887 ,'ye','Jemen','Yemen');
INSERT INTO `Country` (`id`, `sort_name`, `name_ge`, `name_en`) VALUES (894 ,'zm','Sambia','Zambia');
