insert into country (id, sort_name, name_ge, name_en) values
 (4, 'af', 'Afghanistan', 'Afghanistan'),
 (8, 'al', 'Albanien', 'Albania'),
 (12, 'dz', 'Algerien', 'Algeria'),
 (20, 'ad', 'Andorra', 'Andorra'),
 (24, 'ao', 'Angola', 'Angola'),
 (28, 'ag', 'Antigua und Barbuda', 'Antigua and Barbuda'),
 (31, 'az', 'Aserbaidschan', 'Azerbaijan'),
 (32, 'ar', 'Argentinien', 'Argentina'),
 (36, 'au', 'Australien', 'Australia'),
 (40, 'at', 'Österreich', 'Austria'),
 (44, 'bs', 'Bahamas', 'Bahamas'),
 (48, 'bh', 'Bahrain', 'Bahrain'),
 (50, 'bd', 'Bangladesch', 'Bangladesh'),
 (51, 'am', 'Armenien', 'Armenia'),
 (52, 'bb', 'Barbados', 'Barbados'),
 (56, 'be', 'Belgien', 'Belgium'),
 (64, 'bt', 'Bhutan', 'Bhutan'),
 (68, 'bo', 'Bolivien', 'Bolivia'),
 (70, 'ba', 'Bosnien und Herzegowina', 'Bosnia and Herzegovina'),
 (72, 'bw', 'Botswana', 'Botswana'),
 (76, 'br', 'Brasilien', 'Brazil'),
 (84, 'bz', 'Belize', 'Belize'),
 (90, 'sb', 'Salomonen', 'Solomon Islands'),
 (96, 'bn', 'Brunei', 'Brunei Darussalam'),
 (100, 'bg', 'Bulgarien', 'Bulgaria'),
 (104, 'mm', 'Myanmar', 'Myanmar'),
 (108, 'bi', 'Burundi', 'Burundi'),
 (112, 'by', 'Belarus', 'Belarus'),
 (116, 'kh', 'Kambodscha', 'Cambodia'),
 (120, 'cm', 'Kamerun', 'Cameroon'),
 (124, 'ca', 'Kanada', 'Canada'),
 (132, 'cv', 'Kap Verde', 'Cabo Verde'),
 (140, 'cf', 'Zentralafrikanische Republik', 'Central African Republic'),
 (144, 'lk', 'Sri Lanka', 'Sri Lanka'),
 (148, 'td', 'Tschad', 'Chad'),
 (152, 'cl', 'Chile', 'Chile'),
 (156, 'cn', 'Volksrepublik China', 'China'),
 (170, 'co', 'Kolumbien', 'Colombia'),
 (174, 'km', 'Komoren', 'Comoros'),
 (178, 'cg', 'Kongo, Republik', 'Congo'),
 (180, 'cd', 'Kongo', 'Congo'),
 (188, 'cr', 'Costa Rica', 'Costa Rica'),
 (191, 'hr', 'Kroatien', 'Croatia'),
 (192, 'cu', 'Kuba', 'Cuba'),
 (196, 'cy', 'Zypern', 'Cyprus'),
 (203, 'cz', 'Tschechien', 'Czechia'),
 (204, 'bj', 'Benin', 'Benin'),
 (208, 'dk', 'Dänemark', 'Denmark'),
 (212, 'dm', 'Dominica', 'Dominica'),
 (214, 'do', 'Dominikanische Republik', 'Dominican Republic'),
 (218, 'ec', 'Ecuador', 'Ecuador'),
 (222, 'sv', 'El Salvador', 'El Salvador'),
 (226, 'gq', 'Äquatorialguinea', 'Equatorial Guinea'),
 (231, 'et', 'Äthiopien', 'Ethiopia'),
 (232, 'er', 'Eritrea', 'Eritrea'),
 (233, 'ee', 'Estland', 'Estonia'),
 (242, 'fj', 'Fidschi', 'Fiji'),
 (246, 'fi', 'Finnland', 'Finland'),
 (250, 'fr', 'Frankreich', 'France'),
 (262, 'dj', 'Dschibuti', 'Djibouti'),
 (266, 'ga', 'Gabun', 'Gabon'),
 (268, 'ge', 'Georgien', 'Georgia'),
 (270, 'gm', 'Gambia', 'Gambia'),
 (276, 'de', 'Deutschland', 'Germany'),
 (288, 'gh', 'Ghana', 'Ghana'),
 (296, 'ki', 'Kiribati', 'Kiribati'),
 (300, 'gr', 'Griechenland', 'Greece'),
 (308, 'gd', 'Grenada', 'Grenada'),
 (320, 'gt', 'Guatemala', 'Guatemala'),
 (324, 'gn', 'Guinea', 'Guinea'),
 (328, 'gy', 'Guyana', 'Guyana'),
 (332, 'ht', 'Haiti', 'Haiti'),
 (340, 'hn', 'Honduras', 'Honduras'),
 (348, 'hu', 'Ungarn', 'Hungary'),
 (352, 'is', 'Island', 'Iceland'),
 (356, 'in', 'Indien', 'India'),
 (360, 'id', 'Indonesien', 'Indonesia'),
 (364, 'ir', 'Iran', 'Iran'),
 (368, 'iq', 'Irak', 'Iraq'),
 (372, 'ie', 'Irland', 'Ireland'),
 (376, 'il', 'Israel', 'Israel'),
 (380, 'it', 'Italien', 'Italy'),
 (384, 'ci', 'Elfenbeinküste', 'Côte d''Ivoire'),
 (388, 'jm', 'Jamaika', 'Jamaica'),
 (392, 'jp', 'Japan', 'Japan'),
 (398, 'kz', 'Kasachstan', 'Kazakhstan'),
 (400, 'jo', 'Jordanien', 'Jordan'),
 (404, 'ke', 'Kenia', 'Kenya'),
 (408, 'kp', 'Nord Korea', 'North Korea'),
 (410, 'kr', 'Süd Korea', 'South Korea'),
 (414, 'kw', 'Kuwait', 'Kuwait'),
 (417, 'kg', 'Kirgisistan', 'Kyrgyzstan'),
 (418, 'la', 'Laos', 'Lao'),
 (422, 'lb', 'Libanon', 'Lebanon'),
 (426, 'ls', 'Lesotho', 'Lesotho'),
 (428, 'lv', 'Lettland', 'Latvia'),
 (430, 'lr', 'Liberia', 'Liberia'),
 (434, 'ly', 'Libyen', 'Libya'),
 (438, 'li', 'Liechtenstein', 'Liechtenstein'),
 (440, 'lt', 'Litauen', 'Lithuania'),
 (442, 'lu', 'Luxemburg', 'Luxembourg'),
 (450, 'mg', 'Madagaskar', 'Madagascar'),
 (454, 'mw', 'Malawi', 'Malawi'),
 (458, 'my', 'Malaysia', 'Malaysia'),
 (462, 'mv', 'Malediven', 'Maldives'),
 (466, 'ml', 'Mali', 'Mali'),
 (470, 'mt', 'Malta', 'Malta'),
 (478, 'mr', 'Mauretanien', 'Mauritania'),
 (480, 'mu', 'Mauritius', 'Mauritius'),
 (484, 'mx', 'Mexiko', 'Mexico'),
 (492, 'mc', 'Monaco', 'Monaco'),
 (496, 'mn', 'Mongolei', 'Mongolia'),
 (498, 'md', 'Moldau', 'Moldova'),
 (499, 'me', 'Montenegro', 'Montenegro'),
 (504, 'ma', 'Marokko', 'Morocco'),
 (508, 'mz', 'Mosambik', 'Mozambique'),
 (512, 'om', 'Oman', 'Oman'),
 (516, 'na', 'Namibia', 'Namibia'),
 (520, 'nr', 'Nauru', 'Nauru'),
 (524, 'np', 'Nepal', 'Nepal'),
 (528, 'nl', 'Niederlande', 'Netherlands'),
 (548, 'vu', 'Vanuatu', 'Vanuatu'),
 (554, 'nz', 'Neuseeland', 'New Zealand'),
 (558, 'ni', 'Nicaragua', 'Nicaragua'),
 (562, 'ne', 'Niger', 'Niger'),
 (566, 'ng', 'Nigeria', 'Nigeria'),
 (578, 'no', 'Norwegen', 'Norway'),
 (583, 'fm', 'Mikronesien', 'Micronesia'),
 (584, 'mh', 'Marshallinseln', 'Marshall Islands'),
 (585, 'pw', 'Palau', 'Palau'),
 (586, 'pk', 'Pakistan', 'Pakistan'),
 (591, 'pa', 'Panama', 'Panama'),
 (598, 'pg', 'Papua-Neuguinea', 'Papua New Guinea'),
 (600, 'py', 'Paraguay', 'Paraguay'),
 (604, 'pe', 'Peru', 'Peru'),
 (608, 'ph', 'Philippinen', 'Philippines'),
 (616, 'pl', 'Polen', 'Poland'),
 (620, 'pt', 'Portugal', 'Portugal'),
 (624, 'gw', 'Guinea-Bissau', 'Guinea-Bissau'),
 (626, 'tl', 'Osttimor', 'Timor-Leste'),
 (634, 'qa', 'Katar', 'Qatar'),
 (642, 'ro', 'Rumänien', 'Romania'),
 (643, 'ru', 'Russland', 'Russian Federation'),
 (646, 'rw', 'Ruanda', 'Rwanda'),
 (659, 'kn', 'St. Kitts und Nevis', 'Saint Kitts and Nevis'),
 (662, 'lc', 'St. Lucia', 'Saint Lucia'),
 (670, 'vc', 'St. Vincent und die Grenadinen', 'Saint Vincent and the Grenadines'),
 (674, 'sm', 'San Marino', 'San Marino'),
 (678, 'st', 'São Tomé und Príncipe', 'Sao Tome and Principe'),
 (682, 'sa', 'Saudi-Arabien', 'Saudi Arabia'),
 (686, 'sn', 'Senegal', 'Senegal'),
 (688, 'rs', 'Serbien', 'Serbia'),
 (690, 'sc', 'Seychellen', 'Seychelles'),
 (694, 'sl', 'Sierra Leone', 'Sierra Leone'),
 (702, 'sg', 'Singapur', 'Singapore'),
 (703, 'sk', 'Slowakei', 'Slovakia'),
 (704, 'vn', 'Vietnam', 'Viet Nam'),
 (705, 'si', 'Slowenien', 'Slovenia'),
 (706, 'so', 'Somalia', 'Somalia'),
 (710, 'za', 'Südafrika', 'South Africa'),
 (716, 'zw', 'Simbabwe', 'Zimbabwe'),
 (724, 'es', 'Spanien', 'Spain'),
 (728, 'ss', 'Südsudan', 'South Sudan'),
 (729, 'sd', 'Sudan', 'Sudan'),
 (740, 'sr', 'Suriname', 'Suriname'),
 (748, 'sz', 'Eswatini', 'Eswatini'),
 (752, 'se', 'Schweden', 'Sweden'),
 (756, 'ch', 'Schweiz', 'Switzerland'),
 (760, 'sy', 'Syrien', 'Syrian Arab Republic'),
 (762, 'tj', 'Tadschikistan', 'Tajikistan'),
 (764, 'th', 'Thailand', 'Thailand'),
 (768, 'tg', 'Togo', 'Togo'),
 (776, 'to', 'Tonga', 'Tonga'),
 (780, 'tt', 'Trinidad und Tobago', 'Trinidad and Tobago'),
 (784, 'ae', 'Vereinigte Arabische Emirate', 'United Arab Emirates'),
 (788, 'tn', 'Tunesien', 'Tunisia'),
 (792, 'tr', 'Türkei', 'Turkey'),
 (795, 'tm', 'Turkmenistan', 'Turkmenistan'),
 (798, 'tv', 'Tuvalu', 'Tuvalu'),
 (800, 'ug', 'Uganda', 'Uganda'),
 (804, 'ua', 'Ukraine', 'Ukraine'),
 (807, 'mk', 'Nordmazedonien', 'North Macedonia'),
 (818, 'eg', 'Ägypten', 'Egypt'),
 (826, 'gb', 'Vereinigtes Königreich', 'United Kingdom'),
 (834, 'tz', 'Tansania', 'Tanzania, United Republic of'),
 (840, 'us', 'Vereinigte Staaten', 'United States of America'),
 (854, 'bf', 'Burkina Faso', 'Burkina Faso'),
 (858, 'uy', 'Uruguay', 'Uruguay'),
 (860, 'uz', 'Usbekistan', 'Uzbekistan'),
 (862, 've', 'Venezuela', 'Venezuela'),
 (882, 'ws', 'Samoa', 'Samoa'),
 (887, 'ye', 'Jemen', 'Yemen'),
 (894, 'zm', 'Sambia', 'Zambia');